version: '3.3'

services:

  # JUPYTER APPMODE 
  jupyterhub-app:
    image: $DLAB_DOMAIN_SHORT$:5000/jupyterhub_swarm
    build:
      context: ./context/jupyterhub-swarm
    hostname: jupyterhub-app
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - $DLAB_HOME$/toolscfg/jupyter_appmode/hub:/srv/jupyterhub
    networks:
      - $DLAB_NAME$_registry_frontend
    environment:
      DOCKER_NETWORK_NAME: $DLAB_NAME$_registry_frontend
    deploy:
      replicas: 1
      placement:
        constraints: [node.role == manager]

  # this image is for building and pushing only
  # in order to be used by SwarmSpawner appmode
  # this has to be checked
  notebook_image_app:
    image: $DLAB_DOMAIN_SHORT$:5000/jupyterhub_singleuser_app
    build:
      context: ./context/jupyterhub-swarm-single-appmode
    networks:
      - $DLAB_NAME$_registry_frontend
      - $DLAB_NAME$_registry_backend
    deploy:
      replicas: 0

networks:
  $DLAB_NAME$_registry_backend:
    external: true
  $DLAB_NAME$_registry_frontend:
    external: true

